/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Skill { 'id' : string, 'name' : string, 'level' : bigint }
export interface StudyPlan {
  'jobRole' : string,
  'modules' : Array<WeeklyModule>,
}
export interface Task {
  'durationMins' : bigint,
  'title' : string,
  'isCompleted' : boolean,
  'description' : string,
  'associatedSkill' : string,
}
export interface UserProfile {
  'username' : string,
  'targetJobRole' : string,
  'skills' : Array<Skill>,
  'studyGoals' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeeklyModule { 'tasks' : Array<Task>, 'weekNumber' : bigint }
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'analyzeSkillGaps' : ActorMethod<[], [bigint, Array<Skill>]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<
    [string, string, Array<Skill>, string],
    undefined
  >,
  'generateDefaultPlan' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getReadinessScore' : ActorMethod<[], bigint>,
  'getStudyPlan' : ActorMethod<[], [] | [StudyPlan]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markTaskComplete' : ActorMethod<[bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];