/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Skill = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'level' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'targetJobRole' : IDL.Text,
  'skills' : IDL.Vec(Skill),
  'studyGoals' : IDL.Text,
});
export const Task = IDL.Record({
  'durationMins' : IDL.Nat,
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'description' : IDL.Text,
  'associatedSkill' : IDL.Text,
});
export const WeeklyModule = IDL.Record({
  'tasks' : IDL.Vec(Task),
  'weekNumber' : IDL.Nat,
});
export const StudyPlan = IDL.Record({
  'jobRole' : IDL.Text,
  'modules' : IDL.Vec(WeeklyModule),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'analyzeSkillGaps' : IDL.Func([], [IDL.Nat, IDL.Vec(Skill)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(Skill), IDL.Text],
      [],
      [],
    ),
  'generateDefaultPlan' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getReadinessScore' : IDL.Func([], [IDL.Nat], ['query']),
  'getStudyPlan' : IDL.Func([], [IDL.Opt(StudyPlan)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markTaskComplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Skill = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'level' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'targetJobRole' : IDL.Text,
    'skills' : IDL.Vec(Skill),
    'studyGoals' : IDL.Text,
  });
  const Task = IDL.Record({
    'durationMins' : IDL.Nat,
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'description' : IDL.Text,
    'associatedSkill' : IDL.Text,
  });
  const WeeklyModule = IDL.Record({
    'tasks' : IDL.Vec(Task),
    'weekNumber' : IDL.Nat,
  });
  const StudyPlan = IDL.Record({
    'jobRole' : IDL.Text,
    'modules' : IDL.Vec(WeeklyModule),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'analyzeSkillGaps' : IDL.Func([], [IDL.Nat, IDL.Vec(Skill)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(Skill), IDL.Text],
        [],
        [],
      ),
    'generateDefaultPlan' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getReadinessScore' : IDL.Func([], [IDL.Nat], ['query']),
    'getStudyPlan' : IDL.Func([], [IDL.Opt(StudyPlan)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markTaskComplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };